# Permalinks
permalink:           /:title

# Setup
title:               Peluqueria Escandalo
tagline:
url:                 "http://www.peluqueriaescandalozaragoza.es/"
paginate:            1
baseurl:             ""

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
